# Generated by Django 5.0.3 on 2024-04-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_firstname', models.CharField(max_length=200)),
                ('admin_lastname', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_pass', models.CharField(max_length=20)),
                ('admin_accountNum', models.IntegerField()),
                ('admin_LastAccess_DT', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('produced_by', models.CharField(max_length=200)),
                ('product_qty', models.IntegerField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('isRefundable', models.BooleanField(default=False)),
                ('warranty_exp_DT', models.DateTimeField()),
                ('row_insert_DT', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_firstName', models.CharField(max_length=200)),
                ('user_lastName', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_accountNum', models.IntegerField()),
                ('registration_DT', models.DateTimeField()),
                ('user_LastAccess_DT', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('user_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_group_Name', models.CharField(max_length=200)),
                ('user_group_Creation_DT', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inventory_item', models.CharField(max_length=300)),
                ('inventory_item_qty', models.IntegerField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('report_DT', models.DateTimeField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adminuser')),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tbl_name', models.CharField(max_length=300)),
                ('tbl_col', models.CharField(max_length=300)),
                ('tbl_row', models.IntegerField()),
                ('isAdmin', models.BooleanField(default=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adminuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.usergroup')),
            ],
        ),
    ]
